service: serverless-efs-test

custom:
  subnetsId: subnet-324adasd
  securityGroup: sg-234fsfsdf34423

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  iam:
    role: ${file(iamroles/iamroles.yml)}

  environment:
    NODE_PATH: /mnt/efs/node_modules

package:
  exclude:
    - node_modules/**

# Transform: AWS::Serverless-2016-10-31
resources:
  - ${file(resources/efs.yml)}

functions:
  hello:
    handler: handler.hello
    fileSystemConfig:
      arn:
        Fn::GetAtt:
          - AccessPoint
          - Arn
      localMountPath: /mnt/efs
    vpc:
      securityGroupIds:
        - ${self:custom.securityGroup}
      subnetIds:
        - ${self:custom.subnetsId}
    events:
      - http:
          path: hello
          method: get
    dependsOn:
      - MountTarget
# plugins:
#   - serverless-offline
